### ISSUE TITLE
Clarify what X means on supported browsers

### ISSUE THREAD

**Issue by kevinrobinson** [wqian94/AuO#1]
Hello from the Teaching Systems Lab! :)

I was checking this out to see if we could re-use it for Does the X on https://github.com/wqian94/AuO#supported-browsers-and-operating-systems mean that browsers like IE and Safari are unsupported, or fully supported?

Thanks!

**Comment by wqian94** [comment]
Hi, the X's mean that those browsers are currently unsupported. At the moment, Safari, Opera, and Edge do not support the MediaRecorder API, which is required for capturing audio streams in JavaScript.

**Comment by kevinrobinson** [comment]
Cool, thanks!
